# Working with Pandas

Pandas is very useful when working with tables in Python. The main Pandas object is called DataFrame and can be created using the command `pd.DataFrame()` (if the Pandas package was imported as `import pandas as pd`). However, it is more common to use the `pd.read_csv()` function to load data from a file instead of creating it from scratch.

A lot of things happen when `read_csv()` is used, so it is adviced to run sanity checks to ensure the data was loaded as expected. Simplest things that can be done is checking how first and last rows look like by using functions like `head()` and `tail()`. You can also check the number and names of columns.

## Exercises

Download the dataset of animal species:
```bash
!curl -o species.csv https://raw.githubusercontent.com/MainakRepositor/Datasets/refs/heads/master/species.csv
```

1. Import Pandas. Load the downloaded CSV file with Pandas using `read_csv()` function and save its contents into a new variable.
2. Print out first 10 rows - there are two ways of doing that, either with slicing or with a Pandas function. Try both methods.
3. Print out last 10 rows with two different methods.
4. Print out random 10 rows using a relevant Pandas function.
5. Print out all column names.
6. Print out random 10 rows and only these columns: "Category", "Order", "Family", "Scientific Name".

In [3]:
# !pip install numpy

In [4]:
import pandas as pd

In [5]:
raw_data = pd.read_csv('species.csv')

C:\Users\rokas\AppData\Local\Temp\ipykernel_4120\753109943.py:1: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_data = pd.read_csv('species.csv')


In [15]:
cols = ["Category", "Order", "Family", "Scientific Name"]
raw_data.sample(10)[cols]

Category           Order           Family  \
63229   Vascular Plant         Pinales     Cupressaceae   
6696           Reptile        Squamata        Iguanidae   
10423   Vascular Plant    Polypodiales      Woodsiaceae   
102772  Vascular Plant        Lamiales    Orobanchaceae   
35986   Vascular Plant  Ophioglossales  Ophioglossaceae   
111353          Insect     Lepidoptera       Lycaenidae   
24480   Vascular Plant         Vitales         Vitaceae   
101294         Reptile      Testudines      Chelydridae   
7497              Fish    Squaliformes       Dalatiidae   
56355   Vascular Plant         Fabales         Fabaceae   

                    Scientific Name  
63229        Cupressus sempervirens  
6696            Anolis carolinensis  
10423             Woodsia scopulina  
102772         Conopholis americana  
35986         Botrychium multifidum  
111353        Glaucopsyche lygdamus  
24480   Parthenocissus quinquefolia  
101294          Chelydra serpentina  
7497          Isistius brasiliensis  
56355             Senna surattensis

# Pandas data types

Each column of a DataFrame has a data type, so all values of that column have this data type. You can change data types to automatically change values:

In [16]:
df_with_ints = pd.DataFrame([0, 0, 1, 1, 1, 0, 1], columns=['values'])
print(f'Dataframe has one column with values of type: {df_with_ints["values"].dtype}')
print(f'Column values: {df_with_ints["values"].values}\n')

# using astype()

df_with_ints['values_bool'] = df_with_ints['values'].astype(bool)
print(f'By changing column dtype to bool, it got dtype: {df_with_ints["values_bool"].dtype}')
print(f'Column values: {df_with_ints["values_bool"].values}\n')

df_with_ints['values_float'] = df_with_ints['values'].astype(float)
print(f'By changing column dtype to float, it got dtype: {df_with_ints["values_float"].dtype}')
print(f'Column values: {df_with_ints["values_float"].values}\n')

df_with_ints['values_str'] = df_with_ints['values'].astype(str)
print(f'By changing column dtype to str, it got dtype: {df_with_ints["values_str"].dtype}')
print(f'Column values: {df_with_ints["values_str"].values}\n')

# directly changing a value (will be deprecated soon)

df_with_ints['values_changed'] = df_with_ints['values'].copy()
df_with_ints.loc[0, 'values_changed'] = 'changed'
print(f'By directly changing one value to str, the column got dtype: {df_with_ints["values_changed"].dtype}')
print(f'Column values: {df_with_ints["values_changed"].values}\n')

Dataframe has one column with values of type: int64
Column values: [0 0 1 1 1 0 1]

By changing column dtype to bool, it got dtype: bool
Column values: [False False  True  True  True False  True]

By changing column dtype to float, it got dtype: float64
Column values: [0. 0. 1. 1. 1. 0. 1.]

By changing column dtype to str, it got dtype: object
Column values: ['0' '0' '1' '1' '1' '0' '1']

By directly changing one value to str, the column got dtype: object
Column values: ['changed' 0 1 1 1 0 1]



C:\Users\rokas\AppData\Local\Temp\ipykernel_4120\2938539367.py:22: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'changed' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_with_ints.loc[0, 'values_changed'] = 'changed'


Same as for Numpy arrays, one value will affect the whole column:

In [17]:
with open('test.csv', 'w') as f:
  f.writelines(["first_col,second_col,third_col\n", "1,2,3\n", "1,2,hello"])

df = pd.read_csv('test.csv')
print(df.dtypes)
df

first_col      int64
second_col     int64
third_col     object
dtype: object


first_col  second_col third_col
0          1           2         3
1          1           2     hello

In [18]:
df['third_col'].unique()

array(['3', 'hello'], dtype=object)

If some data types of a loaded DataFrame are not expected, the `unique()` function is useful to see all unique values of a column and understand which one might have affected the data type.

## Exercises

1. Check data types of each column in the loaded dataframe.
2. There is a column called "Unnamed: 13". What is inside this column? Print out all its unique values.
3. What other column has the same values as this one? Using a FOR loop, print out unique values for each column.
4. Some columns have a lot of unique values. For each column, print only 5 most commonly repeated values together with their counts, using `value_counts()`.
5. It seems that some values from the "Conservation status" column leaked into the newly created "Unnamed: 13" column. Count how many non-empty values are in "Unnamed: 13".
6. Print out only those rows which have non-empty values in "Unnamed: 13". Try to understand what happenned - how these rows can be repaired so the values are relevant to columns?
7. Save indices of these rows into a new variable.
8. Load the same file without Pandas, by using `open()` and `readlines()` commands, then print out the same problematic rows only using the saved indices. Do you get the same rows?
9. Print out problematic rows using Species ID instead to ensure that the rows correspond to the ones found before.

In [22]:
raw_data['Unnamed: 13'].unique()

array([nan, 'Endangered', 'Threatened', 'Species of Concern'],
      dtype=object)

In [31]:
raw_data['Unnamed: 13'].value_counts()

Unnamed: 13
Threatened            2
Species of Concern    2
Endangered            1
Name: count, dtype: int64

In [51]:
missing_filter = raw_data['Unnamed: 13'].isna()
~missing_filter

0         False
1         False
2         False
3         False
4         False
          ...  
119243    False
119244    False
119245    False
119246    False
119247    False
Name: Unnamed: 13, Length: 119248, dtype: bool

In [54]:
missing_ind = raw_data[~missing_filter].index
missing_ind

Index([6441, 31786, 31826, 44733, 44944], dtype='int64')

In [57]:
missing_filter_12 = raw_data.loc[missing_ind,'Conservation Status'].isna()
missing_filter_12

6441      True
31786    False
31826    False
44733    False
44944     True
Name: Conservation Status, dtype: bool

In [59]:
raw_data[~missing_filter][missing_filter_12] #randa, kur 13 stulpely netruksta, o 12 truksta

Species ID                                    Park Name        Category  \
6441   BISC-1026                       Biscayne National Park          Mammal   
44944  GRSA-1347  Great Sand Dunes National Park and Preserve  Vascular Plant   

             Order        Family     Scientific Name Common Names  \
6441       Sirenia  Trichechidae  Trichechus manatus      Manatee   
44944  Asparagales     Iridaceae  Iris missouriensis    Blue Flag   

      Record Status Occurrence Nativeness Abundance Seasonality  \
6441         Manati   Approved    Present   Unknown     Unknown   
44944     Wild Iris   Approved    Present    Native        Rare   

      Conservation Status         Unnamed: 13  
6441                  NaN          Endangered  
44944                 NaN  Species of Concern

In [63]:
raw_data.loc[~missing_filter & missing_filter_12, 'Conservation Status'] = raw_data[~missing_filter][missing_filter_12]['Unnamed: 13']

In [66]:
raw_data.drop('Unnamed: 13', axis = 1, inplace = True)

In [67]:
raw_data.head()

Species ID             Park Name Category         Order    Family  \
0  ACAD-1000  Acadia National Park   Mammal  Artiodactyla  Cervidae   
1  ACAD-1001  Acadia National Park   Mammal  Artiodactyla  Cervidae   
2  ACAD-1002  Acadia National Park   Mammal     Carnivora   Canidae   
3  ACAD-1003  Acadia National Park   Mammal     Carnivora   Canidae   
4  ACAD-1004  Acadia National Park   Mammal     Carnivora   Canidae   

          Scientific Name                                       Common Names  \
0             Alces alces                                              Moose   
1  Odocoileus virginianus  Northern White-Tailed Deer, Virginia Deer, Whi...   
2           Canis latrans                             Coyote, Eastern Coyote   
3             Canis lupus        Eastern Timber Wolf, Gray Wolf, Timber Wolf   
4           Vulpes vulpes  Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...   

  Record Status     Occurrence  Nativeness Abundance Seasonality  \
0      Approved        Present      Native      Rare    Resident   
1      Approved        Present      Native  Abundant         NaN   
2      Approved        Present  Not Native    Common         NaN   
3      Approved  Not Confirmed      Native       NaN         NaN   
4      Approved        Present     Unknown    Common     Breeder   

  Conservation Status  
0                 NaN  
1                 NaN  
2  Species of Concern  
3          Endangered  
4                 NaN

In [72]:
changed_rows = ~missing_filter&missing_filter_12
changed_index = raw_data.loc[changed_rows].index

In [33]:
# for col in raw_data.columns:
#     print(raw_data[col].value_counts()[:5])

In [75]:
with open('species.csv', 'r', encoding = 'utf-8') as file:
    list_of_data = []
    for line in file:
        list_of_data.append(line)

In [80]:
for index in changed_index.tolist():
    print(index, list_of_data[index])

6441 BISC-1025,Biscayne National Park,Mammal,Rodentia,Sciuridae,Sciurus carolinensis,Eastern Gray Squirrel,Approved,Present,Unknown,Unknown,,,

44944 GRSA-1335,Great Sand Dunes National Park and Preserve,Vascular Plant,Apiales,Apiaceae,Heracleum maximum,"Common Cowparsnip, Cow Parsnip, Cowparsnip",Approved,Present,Native,Unknown,,,



In [81]:
raw_data.loc[~missing_filter & missing_filter_12]

Species ID                                    Park Name        Category  \
6441   BISC-1026                       Biscayne National Park          Mammal   
44944  GRSA-1347  Great Sand Dunes National Park and Preserve  Vascular Plant   

             Order        Family     Scientific Name Common Names  \
6441       Sirenia  Trichechidae  Trichechus manatus      Manatee   
44944  Asparagales     Iridaceae  Iris missouriensis    Blue Flag   

      Record Status Occurrence Nativeness Abundance Seasonality  \
6441         Manati   Approved    Present   Unknown     Unknown   
44944     Wild Iris   Approved    Present    Native        Rare   

      Conservation Status  
6441           Endangered  
44944  Species of Concern

In [ ]:
raw_data.loc[~missing_filter & missing_filter_12

Missing values can be handled in different ways, based on what is known about the data, their amount, importance, etc.. There is no single way to decide what to do with missing values. Pandas suggests two methods: `.dropna()`, which drops missing values, and `.fillna()`, which fills all missing values with a specified one or method. Let's try to replicate this in numpy:
1. Convert the dataframe loaded before to a Numpy array
2. Find all missing values in every column - how many are there?
3. Pick a strategy for handling the missing values in every column based on what you know about it. For the sake of this excercise, your choices are: drop rows, drop columns, fill every value with the previous one, or fill every value with the most common value.

In [82]:
import numpy as np

In [85]:
np.array([[[1, 5, 9, 6],[5, 9, 6, 5]],[[1, 5, 9, 6],[5, 9, 6, 5]]])

array([[[1, 5, 9, 6],
        [5, 9, 6, 5]],

       [[1, 5, 9, 6],
        [5, 9, 6, 5]]])

In [98]:
empty = np.zeros((10, 10))
empty[5, 8] = 15
empty

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 15.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [99]:
np.linspace(5, 10, 100)

array([ 5.        ,  5.05050505,  5.1010101 ,  5.15151515,  5.2020202 ,
        5.25252525,  5.3030303 ,  5.35353535,  5.4040404 ,  5.45454545,
        5.50505051,  5.55555556,  5.60606061,  5.65656566,  5.70707071,
        5.75757576,  5.80808081,  5.85858586,  5.90909091,  5.95959596,
        6.01010101,  6.06060606,  6.11111111,  6.16161616,  6.21212121,
        6.26262626,  6.31313131,  6.36363636,  6.41414141,  6.46464646,
        6.51515152,  6.56565657,  6.61616162,  6.66666667,  6.71717172,
        6.76767677,  6.81818182,  6.86868687,  6.91919192,  6.96969697,
        7.02020202,  7.07070707,  7.12121212,  7.17171717,  7.22222222,
        7.27272727,  7.32323232,  7.37373737,  7.42424242,  7.47474747,
        7.52525253,  7.57575758,  7.62626263,  7.67676768,  7.72727273,
        7.77777778,  7.82828283,  7.87878788,  7.92929293,  7.97979798,
        8.03030303,  8.08080808,  8.13131313,  8.18181818,  8.23232323,
        8.28282828,  8.33333333,  8.38383838,  8.43434343,  8.48